[package]
name = "compute"
version = "0.1.0"
edition = "2024"

[[bin]]
path = "src/bin/main.rs"
name = "breakthrough"

[dependencies]
clap = "4.5.60"
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2"
serde = { version = "1.0", features = ["derive"] }
toml = "1.1.2"
strum = "0.28.0"
strum_macros = "0.28.0"
rayon = "1.11.0"
csv = "1.4.0"
rand = "0.10.0"
